version: '3.8'

networks:
  application_network:

services:
  zookeeper:
    image: elevy/zookeeper:latest
    container_name: zookeeper
    environment:
      MYID: 1
      SERVERS: zookeeper
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
    networks:
      - application_network
    restart: always


  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1   
    ports:
      - "9091:9092"
    environment:
      - KAFKA_LOG_DIRS= /kafka-1
      - KAFKA_BROKER_ID= 1
      - KAFKA_ADVERTISED_HOST_NAME= kafka1
      - KAFKA_ADVERTISED_PORT= 9092
      # - KAFKA_LISTENERS= PLAINTEXT://:9092
      # - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://192.168.99.100:9092
      # - KAFKA_LISTENERS= PLAINTEXT://:9092
      # - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://kafka1:9092
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_LOG_RETENTION_HOURS= 168
      - KAFKA_LOG_RETENTION_BYTES= 100000000
    depends_on:
      - zookeeper
    networks:
      - application_network
    restart: always
 

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2   
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LOG_DIRS= /kafka-2
      - KAFKA_BROKER_ID= 2
      - KAFKA_ADVERTISED_HOST_NAME= kafka2
      # - KAFKA_LISTENERS= PLAINTEXT://:9092
      # - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://kafka2:9092
      - KAFKA_ADVERTISED_PORT= 9092
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_LOG_RETENTION_HOURS= 168
      - KAFKA_LOG_RETENTION_BYTES= 100000000
    depends_on:
      - zookeeper
    networks:
      - application_network
    restart: always

  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3  
    ports:
      - "9093:9092"
    restart: always
    environment:
      - KAFKA_LOG_DIRS= /kafka-3
      - KAFKA_BROKER_ID= 3
      - KAFKA_ADVERTISED_HOST_NAME= kafka3
      # - KAFKA_LISTENERS= PLAINTEXT://:9092
      # - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://kafka3:9092
      - KAFKA_ADVERTISED_PORT= 9092
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181  
      - KAFKA_LOG_RETENTION_HOURS= 168
      - KAFKA_LOG_RETENTION_BYTES= 100000000
    depends_on:
      - zookeeper     
    networks:
      - application_network  